Repository hubzero/hubzero-cms, pull requests merged in 2019-05, with the labels that each got.

#998 [fix] Fixing styles for auth providers on register page
  core/components/com_members/site/language/en-GB/en-GB.com_members.ini
  core/components/com_members/site/views/register/tmpl/default.php
Labels: bug

#1008 [fix] Fixing bad language string
  core/components/com_blog/site/views/entries/tmpl/edit.php
Labels: bug

#1012 [maint] Updating copyright
  core/plugins/wiki/parsermarkdown/composer.json
  core/plugins/wiki/parsermarkdown/language/en-GB/en-GB.plg_wiki_parsermarkdown.ini
  core/plugins/wiki/parsermarkdown/language/en-GB/en-GB.plg_wiki_parsermarkdown.sys.ini
  core/plugins/wiki/parsermarkdown/migrations/Migration20170309162652PlgWikiParsermarkdown.php
  core/plugins/wiki/parsermarkdown/parser.php
  core/plugins/wiki/parsermarkdown/parsermarkdown.php
  core/plugins/wiki/parsermarkdown/parsermarkdown.xml
Labels: maintenance

#829 [feat] Adding changes to use public or private git repos for tools
  core/components/com_tools/site/controllers/admin.php
  core/components/com_tools/site/controllers/pipeline.php
  core/components/com_tools/site/language/en-GB/en-GB.com_tools.ini
  core/components/com_tools/site/views/pipeline/tmpl/create.php
  core/components/com_tools/site/views/pipeline/tmpl/create.xml
  core/components/com_tools/site/views/pipeline/tmpl/status.php
  core/components/com_tools/tables/tool.php
Labels: enhancement, work-in-progress

#1006 [fix] Don't auto-create bundle
  core/components/com_publications/admin/views/items/tmpl/_selectcontent.php
Labels: bug

#1014 [maint] Bumping framework
  core/composer.lock
Labels: maintenance

#1015 [maint] Bumping framework
  core/composer.lock
Labels: maintenance

#1027 [fix] Adding missing 't'
  core/plugins/authentication/facebook/facebook.php
Labels: bug

#1026 [fix] Use `on('load')` instead of `.load()`
  core/components/com_courses/admin/assets/js/certificates.js
  core/components/com_courses/site/assets/js/plugins.js
  core/components/com_groups/site/assets/js/groups.js
  core/components/com_resources/site/assets/js/resources.js
  core/plugins/courses/outline/assets/js/build.js
  core/plugins/members/profile/assets/js/profile.js
  core/plugins/projects/files/assets/js/fileselector.js
Labels: bug

#1025 [fix] Make sure index is set before attempted use
  core/components/com_tools/site/controllers/pipeline.php
Labels: bug

#1024 [fix] Join on page's current version ID
  core/plugins/resources/related/related.php
Labels: bug

#1022 [fix] Use `prop` instead of `attr`
  core/components/com_support/site/assets/js/support.js
Labels: bug

#1019 [fix] Updating base jQuery UI CSS to 1.12.1
  core/assets/css/images/ui-icons_444444_256x240.png
  core/assets/css/images/ui-icons_555555_256x240.png
  core/assets/css/images/ui-icons_777620_256x240.png
  core/assets/css/images/ui-icons_777777_256x240.png
  core/assets/css/images/ui-icons_cc0000_256x240.png
  core/assets/css/images/ui-icons_ffffff_256x240.png
  core/assets/css/jquery.ui.css
  core/assets/css/jquery.ui.min.css
Labels: bug

#1017 [fix] Create & sync system group
  core/components/com_projects/api/controllers/projectsv2_0.php
  core/components/com_projects/models/orm/owner.php
  core/components/com_projects/models/orm/project.php
Labels: bug

#1016 [fix] Update authenitcator CSS for admin login
  core/modules/mod_adminlogin/assets/css/login.css
  core/modules/mod_adminlogin/tmpl/default.php
Labels: bug

#1020 [fix] Should use com_members, not com_users
  core/components/com_checkin/admin/help/en-GB/checkin.phtml
  core/components/com_config/admin/controllers/application.php
  core/components/com_content/admin/help/en-GB/article.phtml
  core/components/com_courses/api/controllers/coursesv1_0.php
  core/components/com_help/admin/views/help/tmpl/overview.php
  core/components/com_members/admin/controllers/accessgroups.php
  core/components/com_members/admin/helpers/html/index.html
  core/components/com_members/admin/helpers/html/users.php
  core/components/com_members/admin/views/notes/tmpl/edit.php
  core/components/com_members/admin/views/quotas/tmpl/editclass.php
  core/components/com_members/admin/views/whosonline/tmpl/display.php
  core/components/com_members/api/controllers/profilesv1_0.php
  core/components/com_members/api/controllers/profilesv1_1.php
  core/components/com_members/helpers/admin.php
  core/components/com_members/migrations/Migration20190505000000ComMembers.php
  core/components/com_members/models/import/record.php
  core/components/com_members/models/note/category.php
  core/components/com_members/models/registration.php
  core/components/com_search/api/controllers/searchv1_0.php
  core/components/com_tools/admin/views/sessions/tmpl/edit.php
Labels: bug

#1021 [fix] Fixing lang strings and refs to com_users
  core/components/com_login/admin/controllers/login.php
  core/components/com_login/site/controllers/auth.php
  core/components/com_login/site/language/en-GB/en-GB.com_login.ini
  core/components/com_login/site/views/login/tmpl/default.xml
  core/components/com_login/site/views/login/tmpl/default_login.php
  core/components/com_login/site/views/userconsent/tmpl/default.php
Labels: bug

#1028 [fix] Force emails to lowercase
  core/components/com_groups/site/controllers/membership.php
Labels: bug

#1034 [feat] Adding group announcements maco
  core/plugins/content/formathtml/macros/group/announcements.php
Labels: enhancement

#1035 [maint] Bumping framework
  core/composer.lock
Labels: maintenance

#1036 [maint] Bumping framework
  core/composer.lock
Labels: maintenance

#1040 [fix] Update to work with new version of jQuery
  core/plugins/projects/files/assets/js/files.js
Labels: bug

#1045 [fix] Allow CCed users to participate in tickets
  core/components/com_support/models/ticket.php
Labels: bug

#1038 [fix] Make sure content has a value
  core/components/com_modules/admin/controllers/modules.php
Labels: bug

#1039 [fix] Add missing methods for setting path
  core/components/com_categories/admin/controllers/categories.php
  core/components/com_categories/admin/views/categories/tmpl/edit.php
  core/components/com_categories/models/category.php
Labels: bug

#1043 [fix] Can't have two `class` attributes
  core/components/com_tools/helpers/html.php
Labels: bug

#1044 [fix] Fixing issue with adding new ACL items
  core/components/com_support/admin/assets/js/edit.js
  core/components/com_support/admin/views/acl/tmpl/display.php
Labels: bug

#1046 [fix] Removing some bad characters
  core/plugins/user/constantcontact/constantcontact.xml
  core/plugins/user/constantcontact/language/en-GB/en-GB.plg_user_constantcontact.ini
Labels: bug

#1047 [fix] Handle cases where group isn't found
  core/components/com_tools/site/controllers/pipeline.php
Labels: bug

#1049 [fix] Adding block to retrieve initial file list
  core/plugins/projects/files/files.php
  core/plugins/projects/files/views/selector/tmpl/default_selectform.php
Labels: bug

#1051 [refactor] Moving COinS microformat to plugin
  core/components/com_resources/helpers/html.php
  core/plugins/resources/about/views/index/tmpl/default.php
  core/plugins/resources/coins/coins.php
  core/plugins/resources/coins/coins.xml
  core/plugins/resources/coins/language/en-GB/en-GB.plg_resources_coins.ini
  core/plugins/resources/coins/language/en-GB/en-GB.plg_resources_coins.sys.ini
  core/plugins/resources/coins/migrations/Migration20170831000000PlgResourcesCoins.php
Labels: refactor

#1052 [fix] Use constants and adding missing docblock
  core/components/com_resources/models/entry.php
Labels: refactor

#1057 [fix] Create some defaults
  core/components/com_tools/tables/tool.php
Labels: bug

#1058 [fix] Change how authorids are generated
  core/components/com_resources/models/author.php
Labels: bug

#1062 [refactor] Load ticket form as needed
  core/components/com_support/helpers/utilities.php
  core/components/com_support/site/assets/css/support.css
  core/components/com_support/site/controllers/tickets.php
  core/components/com_support/site/views/tickets/tmpl/new.php
  core/components/com_support/site/views/tickets/tmpl/save.php
  core/modules/mod_reportproblems/assets/css/mod_reportproblems.css
  core/modules/mod_reportproblems/assets/img/circling-ball-black.gif
  core/modules/mod_reportproblems/assets/js/mod_reportproblems.js
  core/modules/mod_reportproblems/tmpl/default.php
  core/templates/kimera/html/mod_reportproblems/mod_reportproblems.js
Labels: refactor

#1064 [fix] Set positioning against body element
  core/plugins/projects/files/assets/js/files.js
Labels: bug

#1065 [fix] Posted items should be in cite array
  core/plugins/projects/links/views/selector/tmpl/edit.php
Labels: bug

#1068 [fix] Fixing typo in html attribute
  core/components/com_cron/admin/views/jobs/tmpl/edit.php
Labels: bug

#1070 2.2 projects api files
  core/components/com_projects/api/controllers/projectsv2_0.php
Labels: bug

#1071 [fix] Include form validation script
  core/components/com_publications/admin/views/items/tmpl/edit.php
Labels: bug

#1072 [refactor] Moving inline JS to external files
  core/plugins/usage/maps/animation.php
  core/plugins/usage/maps/assets/css/maps.css
  core/plugins/usage/maps/assets/js/animation.js
  core/plugins/usage/maps/assets/js/online.js
  core/plugins/usage/maps/assets/js/tools.js
  core/plugins/usage/maps/assets/js/us-maps.js
  core/plugins/usage/maps/assets/js/web_all.js
  core/plugins/usage/maps/assets/js/web_gradient.js
  core/plugins/usage/maps/assets/js/whoisonline.js
  core/plugins/usage/maps/maps.php
  core/plugins/usage/maps/online.php
  core/plugins/usage/maps/tools.php
  core/plugins/usage/maps/us-maps.php
  core/plugins/usage/maps/views/maps/tmpl/animation.php
  core/plugins/usage/maps/views/maps/tmpl/display.php
  core/plugins/usage/maps/views/maps/tmpl/online.php
  core/plugins/usage/maps/views/maps/tmpl/tools.php
  core/plugins/usage/maps/views/maps/tmpl/us-maps.php
  core/plugins/usage/maps/views/maps/tmpl/web_all.php
  core/plugins/usage/maps/views/maps/tmpl/web_gradient.php
  core/plugins/usage/maps/views/maps/tmpl/whoisonline.php
  core/plugins/usage/maps/web_all.php
  core/plugins/usage/maps/web_gradient.php
  core/plugins/usage/maps/whoisonline.php
Labels: refactor

#1077 [fix] Handle missing names, log user ID
  core/components/com_tags/admin/views/entries/tmpl/edit.php
  core/components/com_tags/models/log.php
Labels: bug

#1079 [fix] Check for stored DOI shoulder first
  core/plugins/resources/about/views/index/tmpl/default.php
Labels: bug

#1085 [fix] Include base modal styles
  core/components/com_groups/site/views/media/tmpl/filelist.php
Labels: bug

#1088 [fix] Set a max height on the module
  core/modules/mod_members/assets/css/mod_members.css
Labels: bug

#1089 [fix] Only check for published categories
  core/components/com_kb/site/router.php
Labels: bug

#1092 [fix] Ensure field has a default value
  core/components/com_menus/models/item.php
Labels: bug

#1095 [fix] Handle rare case method returns `false`
  core/plugins/authentication/certificate/certificate.php
  core/plugins/authentication/cilogon/cilogon.php
  core/plugins/authentication/facebook/facebook.php
  core/plugins/authentication/google/google.php
  core/plugins/authentication/linkedin/linkedin.php
  core/plugins/authentication/orcid/orcid.php
  core/plugins/authentication/pucas/pucas.php
  core/plugins/authentication/scistarter/scistarter.php
  core/plugins/authentication/shibboleth/shibboleth.php
  core/plugins/authentication/twitter/twitter.php
Labels: bug

#1096 [fix] Adding missing language string
  core/components/com_plugins/admin/language/en-GB/en-GB.com_plugins.ini
Labels: bug

#1097 [fix] Removing ref to hard-coded non-existent shoulder
  core/components/com_resources/site/controllers/resources.php
  core/components/com_resources/site/views/view/tmpl/tools.php
  core/plugins/resources/about/views/index/tmpl/default.php
Labels: bug

#1098 [fix] Store parsed comment in alternate attribute
  core/components/com_support/models/comment.php
Labels: bug

#1099 [fix] Reverting change
  core/components/com_resources/admin/views/items/tmpl/edit.php
Labels: bug

#1100 [fix] Tell accessibility devices to not read icons
  core/assets/less/icons.less
Labels: bug

#1101 [fix] Fixes to improve accessibility
  core/assets/less/comments.less
  core/components/com_answers/site/views/questions/tmpl/search.php
  core/components/com_kb/site/views/articles/tmpl/article.php
  core/components/com_poll/site/views/polls/tmpl/display.php
  core/components/com_publications/site/views/browse/tmpl/default.php
  core/templates/kimera/less/_comments.less
Labels: bug

#1102 [fix] Group by fix for MySQL strict mode
  core/components/com_publications/tables/publication.php
Labels: bug

#1103 [feat] Link DOIs
  core/components/com_citations/helpers/format.php
  core/components/com_citations/models/citation.php
Labels: enhancement

#1105 [refactor] Pass `$link` to lang string
  core/components/com_publications/site/controllers/curation.php
  core/components/com_publications/site/language/en-GB/en-GB.com_publications.ini
Labels: refactor
