Repository hubzero/hubzero-cms, pull requests merged in 2019-07, with the labels that each got.

#1160 [fix] Fixing incorrect param name
  core/plugins/support/markdown/markdown.php
Labels: bug

#1161 [fix] Set return value
  core/components/com_login/site/controllers/auth.php
  core/components/com_users/site/controllers/auth.php
Labels: bug

#1164 [fix] Fixing incorrect field attributes
  core/plugins/wiki/parsermarkdown/parsermarkdown.xml
Labels: bug

#1165 [fix] Fixing install button to say 'install'
  core/components/com_installer/admin/views/packages/tmpl/add.php
  core/components/com_installer/admin/views/packages/tmpl/edit.php
Labels: bug

#1166 [maint] Bumping framework.
  core/composer.lock
Labels: maintenance

#1167 [maint] Bumping framework.
  core/composer.lock
Labels: maintenance

#1170 [fix] Fixing incorrect arguments list
  core/components/com_installer/admin/views/packages/tmpl/add.php
  core/components/com_installer/admin/views/packages/tmpl/edit.php
Labels: bug

#1171 [fix] Use version ID instead of publication ID
  core/components/com_publications/admin/controllers/items.php
Labels: bug

#1173 [fix] Reworking migration to handle edge cases
  core/components/com_publications/migrations/Migration20190620000000ComPublications.php
Labels: bug

#1175 [refactor] Moving JS to external files
  core/components/com_groups/admin/views/imports/tmpl/run.php
  core/components/com_members/admin/assets/js/quotas.js
  core/components/com_members/admin/views/quotas/tmpl/display.php
  core/components/com_members/admin/views/quotas/tmpl/edit.php
  core/components/com_modules/admin/assets/js/modules.js
  core/components/com_modules/models/fields/moduleorder.php
Labels: refactor

#1176 [fix] Fixing typo in language key
  core/components/com_courses/config/config.xml
Labels: bug

#1174 [fix] Updating logo
  core/templates/welcome/images/logo.svg
Labels: maintenance

#1177 [feat] Adding ability to remove files from posts
  core/components/com_forum/admin/assets/css/media.css
  core/components/com_forum/admin/assets/js/media.js
  core/components/com_forum/admin/controllers/media.php
  core/components/com_forum/admin/controllers/threads.php
  core/components/com_forum/admin/language/en-GB/en-GB.com_forum.ini
  core/components/com_forum/admin/views/media/tmpl/display.php
  core/components/com_forum/admin/views/media/tmpl/index.html
  core/components/com_forum/admin/views/threads/tmpl/edit.php
Labels: enhancement

#1180 [fix] Handle cases where INI values aren't Mb
  core/components/com_courses/api/controllers/assetv1_0.php
Labels: bug

#1183 [fix] Use publication version ID
  core/plugins/tags/publications/publications.php
Labels: bug

#1182 [fix] USe DOI handle stored with the record
  core/plugins/oaipmh/resources/data/miner.php
Labels: bug

#1181 Update default tagged item sorting field
  core/components/com_tags/admin/controllers/tagged.php
Labels: bug

#1184 [fix] Escape shell arguments
  core/components/com_projects/helpers/githelper.php
Labels: bug

#1189 [fix] Set proper default log, tmp paths
  core/bootstrap/Install/Providers/WizardServiceProvider.php
Labels: bug

#1187 [maint] Updating composer to 1.8.6
  core/bin/composer
Labels: maintenance

#1196 [fix] Create needed path for files to be copied to
  core/components/com_publications/models/attachments/data.php
Labels: bug
