Repository hubzero/hubzero-cms, pull requests merged in 2019-04, with the labels that each got.

#855 [fix] Fixing incorrect API docblocks
  core/components/com_search/api/controllers/searchv1_0.php
  core/components/com_support/api/controllers/commentsv2_0.php
  core/components/com_support/api/controllers/commentsv2_1.php
  core/components/com_tools/api/controllers/sessionsv1_0.php
Labels: bug

#858 [fix] Enable extension but disable module instance
  core/bootstrap/Install/sql/mysql/hubzero.sql
  core/bootstrap/Install/sql/mysql/hz_sample_data.sql
Labels: bug

#860 [fix] Fixes some potentially rare redirect issues
  core/components/com_login/models/login.php
Labels: bug

#862 Disable the standalone checkbox to prevent updating this value
  core/components/com_resources/admin/views/items/tmpl/edit.php
Labels: enhancement

#863 [fix] Syntax fixes found from `php -l`
  core/components/com_groups/admin/controllers/modules.php
  core/components/com_support/admin/controllers/media.php
Labels: bug

#864 [feat] Adding Percona to database driver list
  core/components/com_config/models/forms/application.xml
Labels: enhancement

#865 [fix] Add correct access values to query
  core/components/com_resources/site/controllers/resources.php
Labels: bug

#866 [fix] Fixing query for MySQL strict mode
  core/components/com_tools/tables/zones.php
Labels: bug

#867 [fix] Include core scripts
  core/components/com_storefront/admin/views/collections/tmpl/edit.php
Labels: bug

#871 [feat] Update travis build
  .travis.yml
  core/bin/php_tests.sh
Labels: enhancement, maintenance

#873 [fix] Ensure user is a valid account
  core/components/com_members/api/controllers/toolsv1_0.php
  core/components/com_tools/api/controllers/sessionsv1_0.php
  core/modules/mod_mysessions/helper.php
Labels: bug

#874 [fix] Fixing nested set when new records are added
  core/components/com_groups/admin/controllers/pages.php
Labels: bug

#875 [feat] Adding before & after save events
  core/components/com_citations/admin/controllers/citations.php
  core/components/com_citations/site/controllers/citations.php
Labels: enhancement

#878 [fix] Don't have git report deleted files
  .travis.yml
Labels: maintenance

#879 [fix] Ensure citation journal datum is a string
  core/plugins/projects/links/links.php
Labels: bug

#880 [fix] Ensure citation journal datum is a string
  core/plugins/projects/links/links.php
Labels: bug

#791 [fix] Add ability to ignore DST calculation for events.
  core/components/com_events/models/eventdate.php
  core/plugins/groups/calendar/calendar.php
  core/plugins/groups/calendar/language/en-GB/en-GB.plg_groups_calendar.ini
  core/plugins/groups/calendar/views/calendar/tmpl/details.php
  core/plugins/groups/calendar/views/calendar/tmpl/display.php
  core/plugins/groups/calendar/views/calendar/tmpl/edit.php
Labels: bug

#877 [fix] Only notify reviewers when grant info is set
  core/components/com_projects/site/assets/css/edit.css
  core/components/com_projects/site/assets/js/setup.js
  core/components/com_projects/site/controllers/setup.php
  core/components/com_projects/site/views/setup/tmpl/_edit_grant_info.php
  core/components/com_projects/site/views/setup/tmpl/describe.php
  core/components/com_projects/site/views/setup/tmpl/finalize.php
  core/templates/kimera/html/com_projects/edit.css
Labels: bug

#883 [fix] Determine root path
  core/assets/js/hubzero.js
Labels: enhancement

#886 [feat] Adding more Bootstrap classnames
  core/components/com_blog/site/views/entries/tmpl/delete.php
  core/components/com_blog/site/views/entries/tmpl/edit.php
  core/components/com_groups/site/views/groups/tmpl/delete.php
  core/components/com_members/site/views/profiles/tmpl/browse.php
  core/components/com_members/site/views/profiles/tmpl/raiselimit.php
Labels: enhancement

#890 [fix] Propogate alias change to child paths
  core/components/com_menus/admin/controllers/items.php
  core/components/com_menus/models/item.php
Labels: bug

#888 [fix] Language IDs are strings
  core/components/com_languages/admin/controllers/overrides.php
  core/components/com_languages/models/override.php
Labels: bug

#889 [fix] Make sure var is set before using it
  core/components/com_installer/admin/views/packages/tmpl/edit.php
Labels: bug

#893 [fix] Renaming method to avoid conflicts
  core/plugins/cron/resources/resources.php
Labels: bug

#906 [fix] Ensure proper input type is being used.
  core/plugins/groups/forum/views/categories/tmpl/edit.php
Labels: bug

#905 [fix] Allow user to quit project if not synced with group
  core/plugins/projects/team/views/quit/tmpl/default.php
Labels: bug

#896 [fix] Always insert scope_id as integer
  core/components/com_wiki/models/link.php
Labels: bug

#897 [fix] Removing Help for deprecated functionality
  core/components/com_tools/site/help/en-GB/index.phtml
  core/components/com_tools/site/help/en-GB/java.phtml
Labels: bug

#898 [fix] Get namespace the proper way
  core/components/com_wiki/site/views/pages/tmpl/submenu.php
Labels: bug

#902 [fix] Adding missing language strings
  core/modules/mod_login/language/en-GB/en-GB.mod_login.ini
Labels: bug

#903 [refactor] Add module container
  core/plugins/members/dashboard/assets/css/dashboard.css
  core/plugins/members/dashboard/assets/js/dashboard.js
  core/plugins/members/dashboard/views/display/tmpl/default.php
Labels: enhancement

#911 [fix] jQuery's `live()` method is deprecated
  core/components/com_courses/site/assets/js/plugins.js
  core/components/com_groups/site/assets/js/groups.js
  core/components/com_publications/site/assets/js/video.js
  core/components/com_resources/site/assets/js/hubpresenter.js
  core/components/com_resources/site/assets/js/video.js
Labels: bug

#912 [fix] Catching missed datetime column
  core/components/com_support/migrations/Migration20190411000000ComSupport.php
Labels: bug

#913 [maint] Replacing image with pure CSS
  core/assets/css/layout.css
  core/assets/css/notifications.css
  core/assets/less/layout.less
  core/components/com_courses/site/assets/css/form.css
  core/components/com_resources/site/assets/css/create.css
  core/components/com_tools/site/assets/css/tools.css
  core/plugins/courses/outline/assets/css/build.css
  core/plugins/courses/progress/assets/css/instructor.css
  core/plugins/members/profile/assets/css/profile.css
  core/templates/system/css/main.css
Labels: maintenance

#914 [fix] A couple more fixes for strict mdoe support
  core/components/com_projects/tables/owner.php
  core/components/com_support/site/controllers/queries.php
Labels: bug

#916 [maint] Removing unused script, CSS
  core/assets/css/select2.css
  core/assets/css/select2.min.css
  core/assets/js/select2.js
  core/assets/js/select2.min.js
Labels: maintenance

#918 [maint] Upgrading jQuery(UI) to latest version
  core/assets/js/jquery.js
  core/assets/js/jquery.ui.js
  core/assets/js/jquery.ui.min.js
Labels: maintenance

#922 [fix] Ensure var is set before using
  core/components/com_resources/admin/views/items/tmpl/edit.php
Labels: bug

#925 [style] Making things all purtty like
  core/modules/mod_adminlogin/helper.php
  core/modules/mod_announcements/tmpl/default.php
  core/modules/mod_articles_categories/mod_articles_categories.php
  core/modules/mod_articles_news/tmpl/_item.php
  core/modules/mod_articles_popular/mod_articles_popular.php
  core/modules/mod_billboards/tmpl/default.php
  core/modules/mod_collect/tmpl/collect.php
  core/modules/mod_events_latest/helper.php
  core/modules/mod_events_latest/tmpl/default.php
  core/modules/mod_featuredblog/helper.php
  core/modules/mod_featuredblog/tmpl/default.php
  core/modules/mod_featuredmember/helper.php
  core/modules/mod_featuredquestion/helper.php
  core/modules/mod_featuredquestion/mod_featuredquestion.php
  core/modules/mod_featuredresource/helper.php
  core/modules/mod_feed_youtube/tmpl/default.php
  core/modules/mod_footer/mod_footer.php
  core/modules/mod_grouppages/mod_grouppages.php
  core/modules/mod_groups/helper.php
  core/modules/mod_incremental_registration/helper.php
  core/modules/mod_latest/mod_latest.php
  core/modules/mod_latestblog/helper.php
  core/modules/mod_latestdiscussions/helper.php
  core/modules/mod_latestusage/helper.php
  core/modules/mod_login/helper.php
  core/modules/mod_login/mod_login.php
  core/modules/mod_mycontributions/tmpl/default.php
  core/modules/mod_mycourses/helper.php
  core/modules/mod_mypoints/helper.php
  core/modules/mod_myprojects/mod_myprojects.php
  core/modules/mod_myprojects/tmpl/default.php
  core/modules/mod_myquestions/tmpl/default.php
  core/modules/mod_myresources/tmpl/default.php
  core/modules/mod_mysessions/mod_mysessions.php
  core/modules/mod_mysessions/tmpl/default.php
  core/modules/mod_newsletter/mod_newsletter.php
  core/modules/mod_poll/mod_poll.php
  core/modules/mod_popular/mod_popular.php
  core/modules/mod_popularfaq/tmpl/default.php
  core/modules/mod_popularquestions/tmpl/default.php
  core/modules/mod_quickicon/mod_quickicon.php
  core/modules/mod_recentquestions/tmpl/default.php
  core/modules/mod_related_items/tmpl/default.php
  core/modules/mod_search/mod_search.php
  core/modules/mod_search/tmpl/default.php
  core/modules/mod_slideshow/helper.php
  core/modules/mod_tools/helper.php
  core/modules/mod_toptags/helper.php
  core/modules/mod_toptags/tmpl/default.php
  core/modules/mod_twitterfeed/helper.php
  core/modules/mod_users_latest/tmpl/default.php
  core/modules/mod_version/tmpl/default.php
  core/modules/mod_whosonline/tmpl/default_admin.php
Labels: maintenance

#926 [style] Slapping lipstick on this here pig
  core/templates/kimera/html/com_citations/citations/view.php
  core/templates/kimera/html/com_groups/groups/view.php
  core/templates/kimera/html/com_resources/view/tools.php
  core/templates/kimera/html/com_tools/sessions/session.php
  core/templates/system/cpanel.php
  core/templates/system/group.php
Labels: maintenance

#923 [fix] Only link to current version of wiki page
  core/plugins/resources/related/related.php
Labels: bug

#927 [style] Fixing formatting. Conform. CONFORM.
  core/bootstrap/Cli/aliases.php
  core/bootstrap/Cli/services.php
  core/bootstrap/Files/aliases.php
  core/bootstrap/Files/services.php
  core/bootstrap/Site/Providers/MenuServiceProvider.php
  core/bootstrap/Site/routes.php
  core/bootstrap/Site/services.php
  core/bootstrap/test/start.php
Labels: maintenance

#935 Forum fix and feature
  core/plugins/groups/forum/forum.php
  core/plugins/groups/forum/language/en-GB/en-GB.plg_groups_forum.ini
  core/plugins/groups/forum/views/settings/tmpl/default.php
Labels: bug, enhancement

#937 [fix] Adding language strings
  core/plugins/authentication/certificate/certificate.php
  core/plugins/authentication/certificate/language/en-GB/en-GB.plg_authentication_certificate.ini
  core/plugins/authentication/facebook/facebook.php
  core/plugins/authentication/facebook/language/en-GB/en-GB.plg_authentication_facebook.ini
  core/plugins/authentication/google/google.php
  core/plugins/authentication/google/language/en-GB/en-GB.plg_authentication_google.ini
  core/plugins/authentication/linkedin/language/en-GB/en-GB.plg_authentication_linkedin.ini
  core/plugins/authentication/linkedin/linkedin.php
  core/plugins/authentication/orcid/language/en-GB/en-GB.plg_authentication_orcid.ini
  core/plugins/authentication/orcid/orcid.php
  core/plugins/authentication/pucas/language/en-GB/en-GB.plg_authentication_pucas.ini
  core/plugins/authentication/pucas/pucas.php
  core/plugins/authentication/twitter/language/en-GB/en-GB.plg_authentication_twitter.ini
  core/plugins/authentication/twitter/twitter.php
Labels: bug

#930 [feat] Add ability to collect i2a2 data.
  core/plugins/authentication/pucas/language/en-GB/en-GB.plg_authentication_pucas.ini
  core/plugins/authentication/pucas/pucas.php
  core/plugins/authentication/pucas/pucas.xml
Labels: enhancement

#934 [fix] Add issing `Lang::txt` (or `sprintf`)
  core/plugins/projects/watch/watch.php
Labels: bug

#945 [fix] Add clarifying error message
  core/components/com_tools/site/views/storage/tmpl/filelist.php
Labels: bug

#938 [fix] Adding missing method
  core/components/com_projects/models/orm/project.php
Labels: bug

#940 [fix] Fixing various issues with navigating file list
  core/components/com_groups/admin/assets/js/media.js
  core/components/com_groups/admin/language/en-GB/en-GB.com_groups.ini
  core/components/com_groups/admin/views/media/tmpl/display.php
  core/components/com_groups/admin/views/media/tmpl/list.php
Labels: bug

#941 [maint] Removing unused library
  core/libraries/nusoap/lib/changelog
  core/libraries/nusoap/lib/class.nusoap_base.php
  core/libraries/nusoap/lib/class.soap_fault.php
  core/libraries/nusoap/lib/class.soap_parser.php
  core/libraries/nusoap/lib/class.soap_server.php
  core/libraries/nusoap/lib/class.soap_transport_http.php
  core/libraries/nusoap/lib/class.soap_val.php
  core/libraries/nusoap/lib/class.soapclient.php
  core/libraries/nusoap/lib/class.wsdl.php
  core/libraries/nusoap/lib/class.wsdlcache.php
  core/libraries/nusoap/lib/class.xmlschema.php
  core/libraries/nusoap/lib/nusoap.php
  core/libraries/nusoap/lib/nusoapmime.php
Labels: maintenance

#944 [refactor] Redesigning Projects browse page
  core/components/com_projects/site/assets/css/projects.css
  core/components/com_projects/site/assets/css/standard.css
  core/components/com_projects/site/language/en-GB/en-GB.com_projects.ini
  core/components/com_projects/site/views/projects/tmpl/_item.php
  core/components/com_projects/site/views/projects/tmpl/_list.php
  core/components/com_projects/site/views/projects/tmpl/intro.php
  core/templates/kimera/html/com_projects/projects.css
Labels: refactor

#936 [feat] Adding Bootstrap classed to form elements
  core/components/com_wiki/site/views/comments/tmpl/_comment.php
  core/components/com_wiki/site/views/comments/tmpl/display.php
  core/components/com_wiki/site/views/pages/tmpl/delete.php
  core/components/com_wiki/site/views/pages/tmpl/edit.php
  core/components/com_wiki/site/views/pages/tmpl/rename.php
  core/components/com_wishlist/site/views/wishlists/tmpl/wish.php
  core/plugins/groups/collections/views/collection/tmpl/delete.php
  core/plugins/groups/collections/views/collection/tmpl/edit.php
  core/plugins/groups/collections/views/post/tmpl/delete.php
  core/plugins/groups/collections/views/post/tmpl/edit.php
  core/plugins/groups/collections/views/post/tmpl/repost.php
  core/plugins/members/collections/views/collection/tmpl/delete.php
  core/plugins/members/collections/views/collection/tmpl/edit.php
  core/plugins/members/collections/views/post/tmpl/delete.php
  core/plugins/members/collections/views/post/tmpl/edit.php
  core/plugins/members/collections/views/post/tmpl/repost.php
Labels: enhancement

#946 [maint] Removing redundant DELETE lang strings
  core/components/com_answers/site/views/questions/tmpl/_comment.php
  core/components/com_blog/site/language/en-GB/en-GB.com_blog.ini
  core/components/com_citations/site/controllers/citations.php
  core/components/com_citations/site/language/en-GB/en-GB.com_citations.ini
  core/components/com_citations/site/views/citations/tmpl/browse.php
  core/components/com_collections/site/language/en-GB/en-GB.com_collections.ini
  core/components/com_collections/site/views/collections/tmpl/collections.php
  core/components/com_collections/site/views/collections/tmpl/posts.php
  core/components/com_collections/site/views/posts/tmpl/display.php
  core/components/com_courses/admin/language/en-GB/en-GB.com_courses.ini
  core/components/com_courses/site/language/en-GB/en-GB.com_courses.ini
  core/components/com_courses/site/views/course/tmpl/display.php
  core/components/com_courses/site/views/form/tmpl/index.php
  core/components/com_events/site/language/en-GB/en-GB.com_events.ini
  core/components/com_events/site/views/details/tmpl/default.php
  core/components/com_events/site/views/details/tmpl/modal.php
  core/components/com_tags/admin/language/en-GB/en-GB.com_tags.ini
  core/components/com_wiki/site/language/en-GB/en-GB.com_wiki.ini
  core/components/com_wiki/site/views/comments/tmpl/_comment.php
  core/modules/mod_myquestions/language/en-GB/en-GB.mod_myquestions.ini
  core/modules/mod_myquestions/tmpl/default.php
  core/modules/mod_mysubmissions/language/en-GB/en-GB.mod_mysubmissions.ini
  core/modules/mod_mysubmissions/tmpl/default.php
  core/modules/mod_whatsnew/language/en-GB/en-GB.mod_whatsnew.ini
  core/modules/mod_whatsnew/tmpl/default.php
Labels: maintenance

#950 [feat] Look for `config` directory
  core/components/com_modules/models/module.php
  core/components/com_plugins/models/plugin.php
  core/components/com_templates/admin/controllers/styles.php
Labels: enhancement

#951 [maint] Updating to reflect deleted libraries
  HUBZERO-CREDITS.php
Labels: maintenance

#953 [fix] Add support for submitbutton on listing page
  core/components/com_content/admin/assets/js/content.js
Labels: bug

#954 [fix] Add migration, better error handling
  core/components/com_usage/helpers/helper.php
  core/components/com_usage/migrations/Migration20170901000000ComUsage.php
  core/components/com_usage/site/language/en-GB/en-GB.com_usage.ini
  core/plugins/usage/domainclass/domainclass.php
  core/plugins/usage/domains/domains.php
  core/plugins/usage/partners/partners.php
  core/plugins/usage/region/region.php
Labels: bug

#957 [fix] Changing input to hidden field
  core/components/com_resources/admin/views/items/tmpl/edit.php
Labels: bug

#959 [fix] Fixing query for MySQL strict mode
  core/plugins/resources/related/related.php
Labels: bug

#960 [fix] Make sure needed class is included
  core/components/com_tools/tables/version.php
Labels: bug

#962 [refactor] Use standard notification system
  core/components/com_projects/site/controllers/base.php
Labels: refactor

#963 [fix] Make sure properties exist
  core/plugins/members/dashboard/views/add/tmpl/default.php
Labels: bug

#964 [fix] Little nicer user experience for bad tags
  core/components/com_tags/site/controllers/tags.php
Labels: refactor

#965 [maint] Removing references to personal email
  core/bootstrap/Install/sql/mysql/hubzero.sql
  core/components/com_cart/site/controllers/test.php
  core/components/com_support/models/changelog.php
Labels: maintenance

#971 [maint] Updating plg_authfactors_* copyright
  core/plugins/authfactors/authy/assets/css/enroll.css
  core/plugins/authfactors/authy/assets/js/enroll.js
  core/plugins/authfactors/authy/authy.php
  core/plugins/authfactors/authy/authy.xml
  core/plugins/authfactors/authy/language/en-GB/en-GB.plg_authfactors_authy.sys.ini
  core/plugins/authfactors/authy/migrations/Migration20170831000000PlgAuthfactorsAuthy.php
  core/plugins/authfactors/authy/views/challenge/tmpl/enroll.php
  core/plugins/authfactors/authy/views/challenge/tmpl/verify.php
  core/plugins/authfactors/certificate/certificate.php
  core/plugins/authfactors/certificate/certificate.xml
  core/plugins/authfactors/certificate/language/en-GB/en-GB.plg_authfactors_certificate.sys.ini
  core/plugins/authfactors/certificate/migrations/Migration20170831000000PlgAuthfactorsCertificate.php
Labels: maintenance

#972 [maint] Updating plg_blog_* copyright
  core/plugins/blog/opengraph/language/en-GB/en-GB.plg_blog_opengraph.ini
  core/plugins/blog/opengraph/language/en-GB/en-GB.plg_blog_opengraph.sys.ini
  core/plugins/blog/opengraph/migrations/Migration20180721000000PlgBlogOpengraph.php
  core/plugins/blog/opengraph/opengraph.php
  core/plugins/blog/opengraph/opengraph.xml
  core/plugins/blog/twitter/language/en-GB/en-GB.plg_blog_twitter.ini
  core/plugins/blog/twitter/language/en-GB/en-GB.plg_blog_twitter.sys.ini
  core/plugins/blog/twitter/migrations/Migration20180722000000PlgBlogTwitter.php
  core/plugins/blog/twitter/twitter.php
  core/plugins/blog/twitter/twitter.xml
Labels: maintenance

#979 [fix] Skip plugins that don't have files
  core/components/com_search/models/basic/result/set.php
Labels: bug

#980 [maint] Updating copyright for core assets
  core/assets/css/adminlist.css
  core/assets/css/buttons.css
  core/assets/css/calendar-jos.css
  core/assets/css/columns.css
  core/assets/css/comments.css
  core/assets/css/contentbox.css
  core/assets/css/diagnostics.css
  core/assets/css/documentation.css
  core/assets/css/fontcons.css
  core/assets/css/highlighter.css
  core/assets/css/icons.css
  core/assets/css/introduction.css
  core/assets/css/layout.css
  core/assets/css/notifications.css
  core/assets/css/pagination.css
  core/assets/css/reset.css
  core/assets/css/system.css
  core/assets/css/tablesorter.themes.blue.css
  core/assets/css/tabs.css
  core/assets/css/tags.css
  core/assets/css/toolbox.css
  core/assets/css/tooltip.css
  core/assets/css/voting.css
  core/assets/js/core-uncompressed.js
  core/assets/js/core.js
  core/assets/js/hubzero.js
  core/assets/js/multiselect.js
  core/assets/js/passwordstrength.js
  core/assets/js/switcher-uncompressed.js
  core/assets/js/switcher.js
  core/assets/js/toolbox.js
  core/assets/js/validate-uncompressed.js
  core/assets/js/validate.js
  core/assets/less/buttons.less
  core/assets/less/comments.less
  core/assets/less/diagnostics.less
  core/assets/less/fontcons.less
  core/assets/less/grid.less
  core/assets/less/icons.less
  core/assets/less/introduction.less
  core/assets/less/layout.less
  core/assets/less/mixins.less
  core/assets/less/modal.less
  core/assets/less/notifications.less
  core/assets/less/pagination.less
  core/assets/less/reset.less
  core/assets/less/site.less
  core/assets/less/tabs.less
  core/assets/less/tags.less
  core/assets/less/tooltip.less
  core/assets/less/utilities.less
  core/assets/less/variables.less
  core/assets/less/voting.less
Labels: maintenance

#981 [maint] Updating copyright
  administrator/index.php
  api/index.php
  app/index.php
  index.php
  muse
Labels: maintenance

#982 [maint] Updating copyright
  app/index.php
  core/index.php
  index.php
  muse
Labels: maintenance

#983 [fix] Remove IDs from URL paths
  core/components/com_content/site/router.php
Labels: bug

#985 [fix] Remove problematic chars from dir names
  core/components/com_projects/models/repo.php
Labels: bug

#995 [fix] Add limit to filter querystring
  core/plugins/groups/resources/views/results/tmpl/default.php
Labels: bug

#996 [fix] Show 'unknown' when author can't be found
  core/components/com_content/admin/views/articles/tmpl/default.php
  core/components/com_content/admin/views/articles/tmpl/edit.php
Labels: bug
