Repository hubzero/hubzero-cms, pull requests merged in 2019-03, with the labels that each got.

#769 [refactor] Simplifying themes, toolbar more visible
  core/templates/kameleon/component.php
  core/templates/kameleon/cpanel.php
  core/templates/kameleon/css/browser/ie8.css
  core/templates/kameleon/css/browser/index.html
  core/templates/kameleon/css/common/rtl.css
  core/templates/kameleon/css/component.css
  core/templates/kameleon/css/error.css
  core/templates/kameleon/css/index.css
  core/templates/kameleon/css/login.css
  core/templates/kameleon/css/themes/aqua.css
  core/templates/kameleon/css/themes/blue.css
  core/templates/kameleon/css/themes/bluesteel.css
  core/templates/kameleon/css/themes/charcoal.css
  core/templates/kameleon/css/themes/grape.css
  core/templates/kameleon/css/themes/green.css
  core/templates/kameleon/css/themes/index.html
  core/templates/kameleon/css/themes/lime.css
  core/templates/kameleon/css/themes/olive.css
  core/templates/kameleon/css/themes/orange.css
  core/templates/kameleon/css/themes/pink.css
  core/templates/kameleon/css/themes/purple.css
  core/templates/kameleon/css/themes/purplepowder.css
  core/templates/kameleon/css/themes/red.css
  core/templates/kameleon/css/themes/salmon.css
  core/templates/kameleon/css/themes/wine.css
  core/templates/kameleon/css/themes/yellow.css
  core/templates/kameleon/error.php
  core/templates/kameleon/fonts/index.html
  core/templates/kameleon/html/com_cpanel/cpanel/default.php
  core/templates/kameleon/index.php
  core/templates/kameleon/language/en-GB/index.html
  core/templates/kameleon/language/index.html
  core/templates/kameleon/less/_dark.less
  core/templates/kameleon/less/_fonts.less
  core/templates/kameleon/less/_icons.less
  core/templates/kameleon/less/_menus.less
  core/templates/kameleon/less/_rtl.less
  core/templates/kameleon/less/_themes.less
  core/templates/kameleon/less/_toolbar.less
  core/templates/kameleon/less/_utilities.less
  core/templates/kameleon/less/_variables.less
  core/templates/kameleon/less/component.less
  core/templates/kameleon/less/error.less
  core/templates/kameleon/less/index.less
  core/templates/kameleon/less/login.less
  core/templates/kameleon/login.php
  core/templates/kameleon/migrations/index.html
Labels: enhancement

#788 [fix] Set PHP default timezone
  core/bootstrap/start.php
Labels: bug

#787 [fix] Removing editor buttons where not needed
  core/components/com_answers/admin/views/answers/tmpl/edit.php
  core/components/com_answers/admin/views/questions/tmpl/edit.php
  core/components/com_citations/admin/views/citations/tmpl/edit.php
  core/components/com_collections/admin/views/collections/tmpl/edit.php
  core/components/com_resources/admin/views/items/tmpl/edit.php
  core/components/com_tags/admin/views/entries/tmpl/edit.php
Labels: bug

#786 [fix] Removing deprecated Joomla syntax
  core/components/com_login/models/login.php
Labels: bug

#785 [fix] Fixing queries for MySQL strict mode
  core/components/com_categories/admin/controllers/categories.php
  core/components/com_support/models/tags.php
Labels: bug

#783 [fix] Fixing detemrining if record is checked out
  core/components/com_billboards/admin/views/billboards/tmpl/display.php
Labels: bug

#782 [fix] Remember what page the comments list was for
  core/components/com_wiki/admin/controllers/comments.php
  core/components/com_wiki/admin/views/comments/tmpl/display.php
  core/components/com_wiki/admin/views/comments/tmpl/edit.php
Labels: bug

#781 [fix] Use Hubzero database driver
  core/plugins/projects/databases/databases.php
Labels: bug

#780 [fix] Fixing chart loading when total is zero
  core/components/com_activity/admin/controllers/entries.php
  core/components/com_activity/admin/views/entries/tmpl/display.php
Labels: bug

#779 [fix] Include needed form validation script
  core/components/com_tools/admin/views/versions/tmpl/edit.php
Labels: bug

#775 [fix] Fixing incorrect method name
  core/plugins/wiki/parserdefault/macros/page.php
Labels: bug

#776 [fix] Fixing datetime regex to be stricter
  core/components/com_citations/site/controllers/citations.php
Labels: bug

#778 [fix] Handle missing files a little nicer
  core/components/com_forum/models/attachment.php
  core/components/com_forum/site/language/en-GB/en-GB.com_forum.ini
  core/components/com_forum/site/views/threads/tmpl/_comment.php
  core/plugins/groups/forum/language/en-GB/en-GB.plg_groups_forum.ini
  core/plugins/groups/forum/views/threads/tmpl/_comment.php
Labels: bug

#774 [feat] Updating DB list to match available drivers
  core/components/com_config/models/forms/application.xml
Labels: enhancement

#773 [fix] Fixing query to match what it was before refactor
  core/components/com_services/models/service.php
Labels: bug

#772 [fix] Use proper constructors, getters, setters
  core/components/com_tools/api/controllers/sessionsv1_0.php
Labels: bug

#770 [fix] Fixing issues with checking in tables
  core/components/com_checkin/models/inspector.php
  core/components/com_publications/admin/views/items/tmpl/display.php
Labels: bug

#800 [fix] $this from static context
  core/libraries/joomla/utilities/utility.php
Labels: bug

#794 Remove stray character
  core/components/com_members/admin/controllers/passwordblacklist.php
Labels: bug

#815 [refactor] Guard against query tampering
  core/components/com_wiki/site/controllers/history.php
  core/components/com_wiki/site/controllers/pages.php
  core/plugins/groups/wiki/wiki.php
Labels: refactor

#793 [fix] Moving JS to external file
  core/plugins/system/debug/assets/js/debug.js
  core/plugins/system/debug/debug.php
Labels: bug

#795 2.2 hubzero 11777
  core/bootstrap/Install/config/ftp.php
  core/components/com_config/models/application.php
Labels: bug

#796 [fix] Check for triggers before removing table
  core/migrations/Migration20190305000000HgUpdateQueue.php
  core/migrations/Migration20190318000000HgUpdateQueue.php
Labels: bug

#801 [fix] Update record if thread ID is missing
  core/components/com_forum/models/post.php
Labels: bug

#804 [fix] Removing user ID limitation
  core/plugins/cron/resources/resources.php
Labels: bug

#805 [feat] Adding com_login to list of routing exceptions
  core/plugins/system/incomplete/incomplete.php
  core/plugins/system/password/password.php
  core/plugins/system/spamjail/spamjail.php
  core/plugins/system/unapproved/unapproved.php
  core/plugins/system/unconfirmed/unconfirmed.php
  core/plugins/system/userconsent/userconsent.php
Labels: enhancement

#806 [refactor] Moving twitteroauth lib to plugin
  core/libraries/twitteroauth/OAuth.php
  core/libraries/twitteroauth/twitteroauth.php
  core/plugins/authentication/twitter/twitter.php
  core/plugins/authentication/twitter/twitteroauth/OAuth.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthConsumer.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthDataStore.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthException.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthRequest.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthServer.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthSignatureMethod.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthSignatureMethod_HMAC_SHA1.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthSignatureMethod_PLAINTEXT.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthSignatureMethod_RSA_SHA1.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthToken.php
  core/plugins/authentication/twitter/twitteroauth/TwitterOAuthUtil.php
  core/plugins/authentication/twitter/twitteroauth/twitteroauth.php
Labels: refactor

#807 [refactor] Moving LinkedIn lib to plugin
  core/libraries/simplelinkedin-php/OAuth.php
  core/libraries/simplelinkedin-php/linkedin_3.2.0.class.php
  core/plugins/authentication/linkedin/linkedin.php
  core/plugins/authentication/linkedin/simplelinkedin-php/LinkedInException.php
  core/plugins/authentication/linkedin/simplelinkedin-php/LinkedInOAuthException.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuth.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthConsumer.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthDataStore.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthRequest.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthServer.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthSignatureMethod.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthSignatureMethod_HMAC_SHA1.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthSignatureMethod_PLAINTEXT.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthSignatureMethod_RSA_SHA1.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthToken.php
  core/plugins/authentication/linkedin/simplelinkedin-php/OAuthUtil.php
  core/plugins/authentication/linkedin/simplelinkedin-php/linkedin_3.2.0.class.php
Labels: refactor

#808 [refactor] Replacing Joomla filter with Hubzero
  core/components/com_tools/site/controllers/pipeline.php
  core/plugins/system/highlight/highlight.php
  core/plugins/system/remember/remember.php
Labels: refactor

#809 [feat] Copying views from com_users
  core/components/com_members/site/controllers/profiles.php
  core/components/com_members/site/language/en-GB/en-GB.com_members.ini
  core/components/com_members/site/router.php
  core/components/com_members/site/views/profiles/tmpl/spamjail.php
  core/components/com_members/site/views/profiles/tmpl/unapproved.php
Labels: refactor

#810 [fix] Redirect to correct root path
  core/components/com_users/site/controllers/user.php
  core/components/com_users/site/views/login/view.html.php
Labels: bug

#811 [feat] Plugin to force nofollow attr on external links
  core/plugins/content/externalhref/externalhref.php
  core/plugins/content/externalhref/externalhref.xml
  core/plugins/content/externalhref/index.html
  core/plugins/content/externalhref/language/en-GB/en-GB.plg_content_externalhref.ini
  core/plugins/content/externalhref/language/en-GB/en-GB.plg_content_externalhref.sys.ini
  core/plugins/content/externalhref/migrations/Migration20190319000000PlgContentExternalhref.php
Labels: enhancement

#812 [fix] Load Fontcons font
  core/templates/kameleon/css/login.css
  core/templates/kameleon/less/login.less
Labels: bug

#818 [fix] Adding CSRF token to form
  core/modules/mod_rapid_contact/helper.php
  core/modules/mod_rapid_contact/tmpl/default.php
Labels: bug

#825 [fix] Show all publications in admin view
  core/components/com_publications/admin/controllers/items.php
Labels: bug

#822 [fix] Adding missing line that saves tags
  core/plugins/groups/collections/collections.php
  core/plugins/members/collections/collections.php
Labels: bug

#823 [refactor] Don't use deprecated code to unarchive
  core/components/com_groups/site/controllers/media.php
Labels: refactor

#826 [fix] Get tinymce editor working again
  core/plugins/editors/tinymce/assets/templates/template_list.js
  core/plugins/editors/tinymce/tinymce.php
  core/templates/system/css/editor.css
Labels: bug

#833 [feat] Adding migrations for default content
  core/components/com_projects/migrations/Migration20170902000000ComProjects.php
  core/components/com_publications/migrations/Migration20170902000000ComPublications.php
Labels: enhancement

#834 [maint] Changing default value for datetime fields
  core/components/com_menus/migrations/Migration20170901000000ComMenus.php
  core/migrations/Migration20190321000000Core.php
Labels: refactor

#839 [fix] Remove parts of the template from raw view
  core/components/com_wiki/site/controllers/pages.php
  core/components/com_wiki/site/views/pages/tmpl/display_raw.php
Labels: bug

#836 [fix] Pass all needed data to edit view
  core/components/com_groups/admin/controllers/manage.php
  core/components/com_groups/admin/language/en-GB/en-GB.com_groups.ini
  core/components/com_groups/admin/views/manage/tmpl/edit.php
Labels: bug

#837 [fix] Fixing showing open source download
  core/components/com_resources/site/views/view/tmpl/tools.php
  core/templates/kimera/html/com_resources/view/tools.php
Labels: bug

#838 [maint] Removing unused assets.
  core/assets/images/checked_out.png
  core/assets/images/help.png
  core/components/com_content/site/helpers/icon.php
Labels: maintenance

#840 [fix] Check for referer first. It's not always set
  core/plugins/system/debug/debug.php
Labels: bug

#843 [fix] Fixing issue with updating img, redirect
  core/components/com_courses/site/assets/js/courses.overview.js
  core/components/com_courses/site/controllers/course.php
Labels: bug

#845 [fix] Fixing bug causing collected wiki to error
  core/components/com_collections/models/item.php
Labels: bug

#846 [fix] Removing stray character, make field optional
  core/components/com_redirect/admin/assets/js/redirect.js
  core/components/com_redirect/admin/views/links/tmpl/edit.php
Labels: bug

#847 [fix] Removing HTML comments
  core/plugins/captcha/image/language/en-GB/en-GB.plg_captcha_image.ini
  core/plugins/captcha/image/views/display/tmpl/default.php
Labels: bug

#849 [fix] Point DMCA link to correct location
  core/bootstrap/Install/sql/mysql/hz_sample_data.sql
  core/migrations/Migration20190327000000Footer.php
Labels: bug

#851 [fix] Removing errant `break`
  core/components/com_plugins/models/plugin.php
Labels: bug

#852 [refactor] Moving styles to authenticators
  core/components/com_login/site/assets/css/providers.css
  core/components/com_users/site/assets/css/providers.css
  core/plugins/authentication/certificate/assets/css/certificate.css
  core/plugins/authentication/certificate/certificate.php
  core/plugins/authentication/facebook/assets/css/facebook.css
  core/plugins/authentication/facebook/assets/img/flogo-HexRBG-Wht-58.svg
  core/plugins/authentication/facebook/facebook.php
  core/plugins/authentication/google/assets/css/google.css
  core/plugins/authentication/google/assets/img/btn_google_dark_normal_ios.svg
  core/plugins/authentication/google/google.php
  core/plugins/authentication/hubzero/assets/css/hubzero.css
  core/plugins/authentication/hubzero/assets/img/twitter-sign.svg
  core/plugins/authentication/linkedin/assets/css/linkedin.css
  core/plugins/authentication/linkedin/assets/img/In-White-41px-R.png
  core/plugins/authentication/linkedin/linkedin.php
  core/plugins/authentication/linkedin/simplelinkedin-php/linkedin_3.2.0.class.php
  core/plugins/authentication/orcid/assets/css/orcid.css
  core/plugins/authentication/orcid/assets/img/orcid-sign.svg
  core/plugins/authentication/orcid/orcid.php
  core/plugins/authentication/pucas/assets/css/pucas.css
  core/plugins/authentication/pucas/assets/img/purdue-sign.svg
  core/plugins/authentication/pucas/pucas.php
  core/plugins/authentication/shibboleth/assets/css/shibboleth.css
  core/plugins/authentication/twitter/assets/css/twitter.css
  core/plugins/authentication/twitter/assets/img/twitter-sign.svg
  core/plugins/authentication/twitter/twitter.php
Labels: refactor
